import { clsx } from 'clsx'

export function cn(...inputs) {
  return clsx(inputs)
}

export function createPageUrl(pageName) {
  const routes = {
    'Accueil': '/',
    'Verification': '/verification'
  }
  return routes[pageName] || '/'
}

// Mock airline data - 100 compagnies aériennes
export const mockAirlines = [
  { id: 1, nom: 'Air France', code_iata: 'AF', bagageCabine: { longueur: 55, largeur: 35, hauteur: 25, poids: 12 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 2, nom: 'Lufthansa', code_iata: 'LH', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 3, nom: 'Ryanair', code_iata: 'FR', bagageCabine: { longueur: 40, largeur: 20, hauteur: 25, poids: 10 }, bagageSoute: { longueur: 158, poids: 20 } },
  { id: 4, nom: 'British Airways', code_iata: 'BA', bagageCabine: { longueur: 56, largeur: 45, hauteur: 25, poids: 23 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 5, nom: 'Emirates', code_iata: 'EK', bagageCabine: { longueur: 55, largeur: 38, hauteur: 22, poids: 7 }, bagageSoute: { longueur: 158, poids: 30 } },
  { id: 6, nom: 'KLM', code_iata: 'KL', bagageCabine: { longueur: 55, largeur: 35, hauteur: 25, poids: 12 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 7, nom: 'Turkish Airlines', code_iata: 'TK', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 8 }, bagageSoute: { longueur: 158, poids: 30 } },
  { id: 8, nom: 'Qatar Airways', code_iata: 'QR', bagageCabine: { longueur: 50, largeur: 37, hauteur: 25, poids: 7 }, bagageSoute: { longueur: 158, poids: 30 } },
  { id: 9, nom: 'Singapore Airlines', code_iata: 'SQ', bagageCabine: { longueur: 55, largeur: 35, hauteur: 25, poids: 7 }, bagageSoute: { longueur: 158, poids: 30 } },
  { id: 10, nom: 'American Airlines', code_iata: 'AA', bagageCabine: { longueur: 56, largeur: 36, hauteur: 23, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 11, nom: 'Delta Air Lines', code_iata: 'DL', bagageCabine: { longueur: 56, largeur: 35, hauteur: 23, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 12, nom: 'United Airlines', code_iata: 'UA', bagageCabine: { longueur: 56, largeur: 35, hauteur: 22, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 13, nom: 'Swiss International', code_iata: 'LX', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 14, nom: 'Austrian Airlines', code_iata: 'OS', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 15, nom: 'Alitalia', code_iata: 'AZ', bagageCabine: { longueur: 55, largeur: 35, hauteur: 25, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 16, nom: 'Iberia', code_iata: 'IB', bagageCabine: { longueur: 56, largeur: 45, hauteur: 25, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 17, nom: 'TAP Air Portugal', code_iata: 'TP', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 18, nom: 'SAS', code_iata: 'SK', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 19, nom: 'Finnair', code_iata: 'AY', bagageCabine: { longueur: 56, largeur: 45, hauteur: 25, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 20, nom: 'Air Canada', code_iata: 'AC', bagageCabine: { longueur: 56, largeur: 23, hauteur: 56, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 21, nom: 'Japan Airlines', code_iata: 'JL', bagageCabine: { longueur: 55, largeur: 40, hauteur: 25, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 22, nom: 'All Nippon Airways', code_iata: 'NH', bagageCabine: { longueur: 55, largeur: 40, hauteur: 25, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 23, nom: 'Cathay Pacific', code_iata: 'CX', bagageCabine: { longueur: 56, largeur: 36, hauteur: 23, poids: 7 }, bagageSoute: { longueur: 158, poids: 30 } },
  { id: 24, nom: 'Korean Air', code_iata: 'KE', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 12 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 25, nom: 'Asiana Airlines', code_iata: 'OZ', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 26, nom: 'Thai Airways', code_iata: 'TG', bagageCabine: { longueur: 56, largeur: 45, hauteur: 25, poids: 7 }, bagageSoute: { longueur: 158, poids: 30 } },
  { id: 27, nom: 'Malaysia Airlines', code_iata: 'MH', bagageCabine: { longueur: 56, largeur: 36, hauteur: 23, poids: 7 }, bagageSoute: { longueur: 158, poids: 30 } },
  { id: 28, nom: 'Qantas', code_iata: 'QF', bagageCabine: { longueur: 56, largeur: 36, hauteur: 23, poids: 7 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 29, nom: 'Virgin Atlantic', code_iata: 'VS', bagageCabine: { longueur: 56, largeur: 36, hauteur: 23, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 30, nom: 'Virgin Australia', code_iata: 'VA', bagageCabine: { longueur: 56, largeur: 36, hauteur: 23, poids: 7 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 31, nom: 'EasyJet', code_iata: 'U2', bagageCabine: { longueur: 56, largeur: 45, hauteur: 25, poids: 15 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 32, nom: 'Wizz Air', code_iata: 'W6', bagageCabine: { longueur: 40, largeur: 30, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 20 } },
  { id: 33, nom: 'Vueling', code_iata: 'VY', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 34, nom: 'Norwegian', code_iata: 'DY', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 10 }, bagageSoute: { longueur: 158, poids: 20 } },
  { id: 35, nom: 'Pegasus Airlines', code_iata: 'PC', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 8 }, bagageSoute: { longueur: 158, poids: 20 } },
  { id: 36, nom: 'Etihad Airways', code_iata: 'EY', bagageCabine: { longueur: 50, largeur: 40, hauteur: 25, poids: 7 }, bagageSoute: { longueur: 158, poids: 30 } },
  { id: 37, nom: 'Saudi Arabian Airlines', code_iata: 'SV', bagageCabine: { longueur: 56, largeur: 45, hauteur: 25, poids: 7 }, bagageSoute: { longueur: 158, poids: 32 } },
  { id: 38, nom: 'El Al', code_iata: 'LY', bagageCabine: { longueur: 56, largeur: 45, hauteur: 25, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 39, nom: 'Royal Jordanian', code_iata: 'RJ', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 7 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 40, nom: 'Egypt Air', code_iata: 'MS', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 41, nom: 'South African Airways', code_iata: 'SA', bagageCabine: { longueur: 56, largeur: 36, hauteur: 23, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 42, nom: 'Ethiopian Airlines', code_iata: 'ET', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 7 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 43, nom: 'Kenya Airways', code_iata: 'KQ', bagageCabine: { longueur: 56, largeur: 45, hauteur: 25, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 44, nom: 'Royal Air Maroc', code_iata: 'AT', bagageCabine: { longueur: 55, largeur: 35, hauteur: 25, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 45, nom: 'Tunisair', code_iata: 'TU', bagageCabine: { longueur: 55, largeur: 35, hauteur: 25, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 46, nom: 'Air Algérie', code_iata: 'AH', bagageCabine: { longueur: 55, largeur: 35, hauteur: 25, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 47, nom: 'LATAM Airlines', code_iata: 'LA', bagageCabine: { longueur: 55, largeur: 35, hauteur: 25, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 48, nom: 'Avianca', code_iata: 'AV', bagageCabine: { longueur: 55, largeur: 35, hauteur: 25, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 49, nom: 'Copa Airlines', code_iata: 'CM', bagageCabine: { longueur: 56, largeur: 36, hauteur: 23, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 50, nom: 'Aeromexico', code_iata: 'AM', bagageCabine: { longueur: 55, largeur: 40, hauteur: 25, poids: 10 }, bagageSoute: { longueur: 158, poids: 25 } },
  { id: 51, nom: 'Air India', code_iata: 'AI', bagageCabine: { longueur: 55, largeur: 35, hauteur: 25, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 52, nom: 'IndiGo', code_iata: '6E', bagageCabine: { longueur: 55, largeur: 35, hauteur: 25, poids: 7 }, bagageSoute: { longueur: 158, poids: 15 } },
  { id: 53, nom: 'SpiceJet', code_iata: 'SG', bagageCabine: { longueur: 55, largeur: 35, hauteur: 25, poids: 7 }, bagageSoute: { longueur: 158, poids: 15 } },
  { id: 54, nom: 'Vistara', code_iata: 'UK', bagageCabine: { longueur: 55, largeur: 35, hauteur: 25, poids: 7 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 55, nom: 'Air Asia', code_iata: 'AK', bagageCabine: { longueur: 56, largeur: 36, hauteur: 23, poids: 7 }, bagageSoute: { longueur: 158, poids: 20 } },
  { id: 56, nom: 'Cebu Pacific', code_iata: '5J', bagageCabine: { longueur: 56, largeur: 36, hauteur: 23, poids: 7 }, bagageSoute: { longueur: 158, poids: 20 } },
  { id: 57, nom: 'Philippine Airlines', code_iata: 'PR', bagageCabine: { longueur: 56, largeur: 36, hauteur: 23, poids: 7 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 58, nom: 'Vietnam Airlines', code_iata: 'VN', bagageCabine: { longueur: 56, largeur: 36, hauteur: 23, poids: 7 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 59, nom: 'Jetstar', code_iata: 'JQ', bagageCabine: { longueur: 56, largeur: 36, hauteur: 23, poids: 7 }, bagageSoute: { longueur: 158, poids: 20 } },
  { id: 60, nom: 'Scoot', code_iata: 'TR', bagageCabine: { longueur: 54, largeur: 38, hauteur: 23, poids: 10 }, bagageSoute: { longueur: 158, poids: 20 } },
  { id: 61, nom: 'China Eastern', code_iata: 'MU', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 62, nom: 'China Southern', code_iata: 'CZ', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 63, nom: 'Air China', code_iata: 'CA', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 64, nom: 'Hainan Airlines', code_iata: 'HU', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 65, nom: 'Xiamen Airlines', code_iata: 'MF', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 66, nom: 'Aeroflot', code_iata: 'SU', bagageCabine: { longueur: 55, largeur: 40, hauteur: 25, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 67, nom: 'S7 Airlines', code_iata: 'S7', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 68, nom: 'Ural Airlines', code_iata: 'U6', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 5 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 69, nom: 'Rossiya Airlines', code_iata: 'FV', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 70, nom: 'Ukraine International', code_iata: 'PS', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 71, nom: 'LOT Polish Airlines', code_iata: 'LO', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 72, nom: 'Czech Airlines', code_iata: 'OK', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 73, nom: 'Tarom', code_iata: 'RO', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 74, nom: 'Bulgaria Air', code_iata: 'FB', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 75, nom: 'Croatia Airlines', code_iata: 'OU', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 76, nom: 'Air Serbia', code_iata: 'JU', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 77, nom: 'Montenegro Airlines', code_iata: 'YM', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 78, nom: 'Aegean Airlines', code_iata: 'A3', bagageCabine: { longueur: 56, largeur: 45, hauteur: 25, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 79, nom: 'Cyprus Airways', code_iata: 'CY', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 80, nom: 'Air Malta', code_iata: 'KM', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 81, nom: 'Icelandair', code_iata: 'FI', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 82, nom: 'WOW Air', code_iata: 'WW', bagageCabine: { longueur: 54, largeur: 38, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 20 } },
  { id: 83, nom: 'Condor', code_iata: 'DE', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 8 }, bagageSoute: { longueur: 158, poids: 20 } },
  { id: 84, nom: 'Eurowings', code_iata: 'EW', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 8 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 85, nom: 'TUIfly', code_iata: 'X3', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 6 }, bagageSoute: { longueur: 158, poids: 20 } },
  { id: 86, nom: 'Transavia', code_iata: 'HV', bagageCabine: { longueur: 55, largeur: 40, hauteur: 25, poids: 10 }, bagageSoute: { longueur: 158, poids: 20 } },
  { id: 87, nom: 'Jet2', code_iata: 'LS', bagageCabine: { longueur: 56, largeur: 45, hauteur: 25, poids: 10 }, bagageSoute: { longueur: 158, poids: 22 } },
  { id: 88, nom: 'Flybe', code_iata: 'BE', bagageCabine: { longueur: 55, largeur: 35, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 20 } },
  { id: 89, nom: 'Blue Air', code_iata: '0B', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 90, nom: 'Volotea', code_iata: 'V7', bagageCabine: { longueur: 55, largeur: 40, hauteur: 20, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 91, nom: 'Frontier Airlines', code_iata: 'F9', bagageCabine: { longueur: 61, largeur: 40, hauteur: 25, poids: 7 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 92, nom: 'Spirit Airlines', code_iata: 'NK', bagageCabine: { longueur: 56, largeur: 46, hauteur: 25, poids: 7 }, bagageSoute: { longueur: 158, poids: 18 } },
  { id: 93, nom: 'JetBlue Airways', code_iata: 'B6', bagageCabine: { longueur: 56, largeur: 35, hauteur: 22, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 94, nom: 'Southwest Airlines', code_iata: 'WN', bagageCabine: { longueur: 61, largeur: 40, hauteur: 25, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 95, nom: 'Alaska Airlines', code_iata: 'AS', bagageCabine: { longueur: 56, largeur: 35, hauteur: 23, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 96, nom: 'Hawaiian Airlines', code_iata: 'HA', bagageCabine: { longueur: 56, largeur: 35, hauteur: 23, poids: 11 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 97, nom: 'Allegiant Air', code_iata: 'G4', bagageCabine: { longueur: 56, largeur: 36, hauteur: 23, poids: 7 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 98, nom: 'Sun Country Airlines', code_iata: 'SY', bagageCabine: { longueur: 56, largeur: 36, hauteur: 23, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 99, nom: 'Breeze Airways', code_iata: 'MX', bagageCabine: { longueur: 56, largeur: 35, hauteur: 22, poids: 10 }, bagageSoute: { longueur: 158, poids: 23 } },
  { id: 100, nom: 'Porter Airlines', code_iata: 'PD', bagageCabine: { longueur: 55, largeur: 40, hauteur: 23, poids: 7 }, bagageSoute: { longueur: 158, poids: 23 } }
]